version: "3.12"
services:
  app:
    build: .
    container_name: python-server
    command: uvicorn src.main:app --host 0.0.0.0 --port 81 --reload
    ports:
      - "81:81"
    volumes:
      - .:/code
